version: '3'

services:

  client:
    build: client/
    depends_on:
      - 'api'
    ports: 
      - '8080:8080'

  api:
    build: api/
    links:
      - 'db:db'
    depends_on:
      - 'db'
    ports: 
      - '7500:7500'

  db:
    build: db/